Repository GSM-MSG/GAuth-FrontEnd, pull requests merged in 2023-04, with the labels that each got.

#105 🔀설명 페이지의 코드블럭 디자인 수정
  src/components/InstructionPage/style.ts
Labels: 🎨 Type: Publishing, ⚡️Type: Simple, 3️⃣ Priority: Low

#109 🔀 SEO 향상
  src/components/SEO/index.tsx
  src/pages/[notion].tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/instruction.tsx
  src/pages/login.tsx
  src/pages/myprofile.tsx
  src/pages/newpsw.tsx
  src/pages/newservice.tsx
  src/pages/signUp.tsx
Labels: ⚡️Type: Performance

#108 🔀 에러 문구 추가
  src/components/NewSignIn/index.tsx
Labels: 🐞 Type: Bug, 2️⃣ Priority: Medium

#115 🔀 서비스 수정 요청에 redirectUri값 할당
  src/components/MyServiceList/Modify/index.tsx
Labels: 🐞 Type: Bug, 0️⃣ Priority: Critical
