Repository GSM-MSG/GAuth-FrontEnd, pull requests merged in 2023-09, with the labels that each got.

#173 🔀 서비스 커스텀 이미지 등록 기능 추가
  public/font/Pretendard-Black.otf
  public/font/Pretendard-Bold.otf
  public/font/Pretendard-ExtraBold.otf
  public/font/Pretendard-ExtraLight.otf
  public/font/Pretendard-Light.otf
  public/font/Pretendard-Medium.otf
  public/font/Pretendard-Regular.otf
  public/font/Pretendard-SemiBold.otf
  public/font/Pretendard-Thin.otf
  public/png/DefalutImg.png
  public/png/NoImage.png
  public/svg/AddServiceImg.tsx
  public/svg/DeleteServiceImg.tsx
  public/svg/ServicePrivate.tsx
  public/svg/ServicePublic.tsx
  public/svg/index.ts
  src/components/MyServiceList/ListItem.tsx
  src/components/MyServiceList/Modify/index.tsx
  src/components/MyServiceList/Modify/style.ts
  src/components/MyServiceList/style.ts
  src/components/NewService/InfoModal/index.tsx
  src/components/NewService/index.tsx
  src/components/NewService/style.ts
  src/components/ServiceList/ListItem.tsx
  src/components/ServiceList/style.ts
  src/styles/GlobalStyle.tsx
  src/types/ClientInForm.ts
  src/types/ResAddService.ts
Labels: ✨ Type: Feature, 🎨 Type: Publishing, ⚙ Type: Setting

#174 🔀 Deploy
  public/font/Pretendard-Black.otf
  public/font/Pretendard-Bold.otf
  public/font/Pretendard-ExtraBold.otf
  public/font/Pretendard-ExtraLight.otf
  public/font/Pretendard-Light.otf
  public/font/Pretendard-Medium.otf
  public/font/Pretendard-Regular.otf
  public/font/Pretendard-SemiBold.otf
  public/font/Pretendard-Thin.otf
  public/png/DefalutImg.png
  public/png/NoImage.png
  public/svg/AddServiceImg.tsx
  public/svg/DeleteServiceImg.tsx
  public/svg/ServicePrivate.tsx
  public/svg/ServicePublic.tsx
  public/svg/index.ts
  src/components/MyServiceList/ListItem.tsx
  src/components/MyServiceList/Modify/index.tsx
  src/components/MyServiceList/Modify/style.ts
  src/components/MyServiceList/style.ts
  src/components/NewService/InfoModal/index.tsx
  src/components/NewService/index.tsx
  src/components/NewService/style.ts
  src/components/ServiceList/ListItem.tsx
  src/components/ServiceList/style.ts
  src/styles/GlobalStyle.tsx
  src/types/ClientInForm.ts
  src/types/ResAddService.ts
Labels: 🌏 Type: Deploy

#175 🔀 서비스 수정 반응형
  src/components/MyServiceList/Modify/style.ts
Labels: 🎨 Type: Publishing, 1️⃣ Priority: High

#176 🔀 Deploy
  src/components/MyServiceList/Modify/style.ts
Labels: 🌏 Type: Deploy

#177 :twisted_rightwards_arrows: 로그인 불가 메세지 변경
  src/components/SignIn/index.tsx
Labels: 📝 Type: Docs, 1️⃣ Priority: High

#178 🔀 서비스명 수정에서 제한 글자 수 초과시 에러메시지 출력
  src/components/MyProfilePage/style.ts
  src/components/MyServiceList/Modify/index.tsx
Labels: 🐞 Type: Bug, 1️⃣ Priority: High
