Repository GSM-MSG/GAuth-FrontEnd, pull requests merged in 2023-03, with the labels that each got.

#49 🔀 API 수정
  src/api/TokenManger.ts
  src/api/index.ts
  src/components/LoginPage/index.tsx
  src/components/MyProfilePage/index.tsx
  src/components/MyServiceList/ModifyMyService.tsx
  src/components/NewService/index.tsx
  src/components/ServiceList/ListTable.tsx
  src/components/Sidebar/index.tsx
  src/components/SignUpPage/index.tsx
  src/components/VerifyEmail/index.tsx
  src/hooks/useUser.ts
  src/lib/API.tsx
  src/types/TokenType.ts
  src/types/index.ts
Labels: ⚡️ Simple

#47 🔀비밀번호 정규식 수정
  src/components/SignUpPage/index.tsx
Labels: ⚡️ Simple

#53 🔀 다중 이메일 요청 방지 기능 추가
  src/components/SignUpPage/index.tsx
Labels: enhancement

#55 🔀로그인 form에서 이메일 maxLength 삭제
  src/components/LoginPage/index.tsx
Labels: ⚡️ Simple

#54 🔀 로그인 페이지 라우팅 방식 수정
  src/components/LoginPage/index.tsx
  src/components/LoginPage/style.ts
  src/components/SignUpPage/index.tsx
  src/components/SignUpPage/style.ts
  src/lib/OauthQuery.ts
Labels: enhancement, Question

#56 🔀긴급 pr
  src/api/TokenManger.ts
  src/api/index.ts
  src/components/LoginPage/index.tsx
  src/components/LoginPage/style.ts
  src/components/MyProfilePage/index.tsx
  src/components/MyServiceList/ModifyMyService.tsx
  src/components/NewService/index.tsx
  src/components/ServiceList/ListTable.tsx
  src/components/Sidebar/index.tsx
  src/components/SignUpPage/index.tsx
  src/components/SignUpPage/style.ts
  src/components/VerifyEmail/index.tsx
  src/hooks/useUser.ts
  src/lib/API.tsx
  src/lib/OauthQuery.ts
  src/types/TokenType.ts
  src/types/index.ts
Labels: 🌏 Deploy

#61 🔀 회원가입 이메일 최대 길이 삭제
  src/components/SignUpPage/index.tsx
Labels: Bug

#59 🔀 develop to main
  src/components/SignUpPage/index.tsx
Labels: ⚡️ Simple

#62 🔀 Update denpendency
  package.json
  src/api/index.ts
  yarn.lock
Labels: ⚡️ Simple

#63 🔀로그인 페이지 query 처리 수정
  src/components/LoginPage/index.tsx
  src/components/SignUpPage/index.tsx
Labels: Bug, ⚡️ Simple

#65 사이드바 리 디자인 생성
  public/svg/AddService.tsx
  public/svg/Instruction.tsx
  public/svg/Logout.tsx
  public/svg/My.tsx
  public/svg/ServiceList.tsx
  public/svg/SideBarLogo.tsx
  src/components/MyServiceList/ListItem.tsx
  src/components/ServiceList/ListItem.tsx
  src/components/Sidebar/index.tsx
  src/components/Sidebar/style.ts
Labels: ⚡️ Simple

#60 🔀 리디자인 추가
  public/svg/ImageUpload.tsx
  public/svg/NewLogo.tsx
  public/svg/index.ts
  src/Atom/Atoms.tsx
  src/api/TokenManger.ts
  src/api/index.ts
  src/components/LoginPage/index.tsx
  src/components/MyProfilePage/index.tsx
  src/components/MyServiceList/ModifyMyService.tsx
  src/components/NewFindPsw/NewPassword.tsx
  src/components/NewFindPsw/index.tsx
  src/components/NewFindPsw/style.ts
  src/components/NewSignIn/index.tsx
  src/components/NewSignUp/NewPassword.tsx
  src/components/NewSignUp/Notion.tsx
  src/components/NewSignUp/Privacy.tsx
  src/components/NewSignUp/Profile.tsx
  src/components/NewSignUp/Success.tsx
  src/components/NewSignUp/index.tsx
  src/components/NewSignUp/style.ts
  src/components/Sidebar/index.tsx
  src/components/SignUpPage/index.tsx
  src/components/VerifyEmail/index.tsx
  src/components/common/Auth/NewPasswordCommon.tsx
  src/components/common/Auth/SearchEmail.tsx
  src/components/common/Auth/VerifyEmail.tsx
  src/components/common/Auth/style.ts
  src/components/common/CreateTitle/index.tsx
  src/components/common/CreateTitle/style.ts
  src/components/common/Input/index.tsx
  src/components/common/Input/style.ts
  src/components/common/Loading/index.tsx
  src/components/common/Loading/style.ts
  src/lib/PrivacyInfo.tsx
  src/pages/login.tsx
  src/pages/newpsw.tsx
  src/pages/signUp.tsx
  src/types/ErrorType.ts
  src/types/SignUpType.ts
  src/types/index.ts
Labels: enhancement

#66 🔀 Develop
  package.json
  public/svg/AddService.tsx
  public/svg/ImageUpload.tsx
  public/svg/Instruction.tsx
  public/svg/Logout.tsx
  public/svg/My.tsx
  public/svg/NewLogo.tsx
  public/svg/ServiceList.tsx
  public/svg/SideBarLogo.tsx
  public/svg/index.ts
  src/Atom/Atoms.tsx
  src/api/TokenManger.ts
  src/api/index.ts
  src/components/LoginPage/index.tsx
  src/components/MyProfilePage/index.tsx
  src/components/MyServiceList/ListItem.tsx
  src/components/MyServiceList/ModifyMyService.tsx
  src/components/NewFindPsw/NewPassword.tsx
  src/components/NewFindPsw/index.tsx
  src/components/NewFindPsw/style.ts
  src/components/NewSignIn/index.tsx
  src/components/NewSignUp/NewPassword.tsx
  src/components/NewSignUp/Notion.tsx
  src/components/NewSignUp/Privacy.tsx
  src/components/NewSignUp/Profile.tsx
  src/components/NewSignUp/Success.tsx
  src/components/NewSignUp/index.tsx
  src/components/NewSignUp/style.ts
  src/components/ServiceList/ListItem.tsx
  src/components/Sidebar/index.tsx
  src/components/Sidebar/style.ts
  src/components/SignUpPage/index.tsx
  src/components/VerifyEmail/index.tsx
  src/components/common/Auth/NewPasswordCommon.tsx
  src/components/common/Auth/SearchEmail.tsx
  src/components/common/Auth/VerifyEmail.tsx
  src/components/common/Auth/style.ts
  src/components/common/CreateTitle/index.tsx
  src/components/common/CreateTitle/style.ts
  src/components/common/Input/index.tsx
  src/components/common/Input/style.ts
  src/components/common/Loading/index.tsx
  src/components/common/Loading/style.ts
  src/lib/PrivacyInfo.tsx
  src/pages/login.tsx
  src/pages/newpsw.tsx
  src/pages/signUp.tsx
  src/types/ErrorType.ts
  src/types/SignUpType.ts
  src/types/index.ts
  yarn.lock
Labels: 🌏 Deploy

#67 API 오류 수정
  src/api/TokenManger.ts
  src/api/index.ts
Labels: Bug

#68 🔀 hotfix
  src/api/TokenManger.ts
  src/api/index.ts
Labels: 🌏 Deploy

#69 🔀 메인페이지 새 스타일 적용
  next.config.js
  src/components/ServiceList/ListItem.tsx
  src/components/ServiceList/ListTable.tsx
  src/components/ServiceList/index.tsx
  src/components/ServiceList/style.ts
  src/components/Sidebar/index.tsx
  src/components/Sidebar/style.ts
Labels: ⚡️ Simple

#77 🔀 Input errors message 추가
  src/components/NewSignIn/index.tsx
  src/components/common/Auth/NewPasswordCommon.tsx
  src/components/common/Input/index.tsx
Labels: ✨ Type: Feature, ⚡️Type: Simple

#72 🔀 모달 이동 훅 추가
  src/components/NewFindPsw/NewPassword.tsx
  src/components/NewSignIn/index.tsx
  src/components/NewSignUp/Privacy.tsx
  src/components/NewSignUp/Success.tsx
  src/components/common/Auth/NewPasswordCommon.tsx
  src/components/common/Auth/SearchEmail.tsx
  src/components/common/Auth/VerifyEmail.tsx
  src/hooks/useResetModal.ts
Labels: 🐞 Type: Bug, ✨ Type: Feature, 2️⃣ Priority: Medium

#80 🔀 오타 수정
  src/components/NewSignIn/index.tsx
Labels: ♻️ Type: Refactor, ⚡️Type: Simple, 3️⃣ Priority: Low

#81 🔀 자동 로그인 기능 추가
  src/api/TokenManger.ts
  src/api/index.ts
  src/components/NewFindPsw/index.tsx
  src/components/NewSignIn/index.tsx
  src/components/NewSignIn/style.ts
  src/components/NewSignUp/index.tsx
  src/hooks/useAutoLogin.ts
  src/types/TokenMangerType.ts
Labels: ✨ Type: Feature, 🌏 Type: Deploy, 0️⃣ Priority: Critical

#73 🔀 Portal 추가
  src/components/MyProfilePage/index.tsx
  src/components/common/Portal/index.tsx
  src/components/common/Portal/style.ts
  src/pages/_document.tsx
Labels: ✨ Type: Feature, 🎨 Type: Publishing

#82 🔀 Develop
  src/api/TokenManger.ts
  src/api/index.ts
  src/components/MyProfilePage/index.tsx
  src/components/NewFindPsw/NewPassword.tsx
  src/components/NewFindPsw/index.tsx
  src/components/NewSignIn/index.tsx
  src/components/NewSignIn/style.ts
  src/components/NewSignUp/Privacy.tsx
  src/components/NewSignUp/Success.tsx
  src/components/NewSignUp/index.tsx
  src/components/common/Auth/NewPasswordCommon.tsx
  src/components/common/Auth/SearchEmail.tsx
  src/components/common/Auth/VerifyEmail.tsx
  src/components/common/Input/index.tsx
  src/components/common/Portal/index.tsx
  src/components/common/Portal/style.ts
  src/hooks/useAutoLogin.ts
  src/hooks/useResetModal.ts
  src/pages/_document.tsx
  src/types/TokenMangerType.ts
Labels: ✨ Type: Feature, ⚡️Type: Performance, 🌏 Type: Deploy

#84 🔀 Portal Add stopPropagation
  src/components/common/Portal/index.tsx
Labels: 🐞 Type: Bug, 0️⃣ Priority: Critical

#88 🔀 비밀번호 체크 기능 추가
  src/components/NewSignIn/index.tsx
  src/components/common/Auth/NewPasswordCommon.tsx
  src/components/common/Input/index.tsx
  src/components/common/Input/style.ts
Labels: ✨ Type: Feature, ⚡️Type: Simple

#85 🔀 새서비스 페이지 리디자인
  public/svg/AddServiceFormImg.tsx
  public/svg/CheckIcon.tsx
  public/svg/index.ts
  src/components/NewService/InfoModal/Info.tsx
  src/components/NewService/InfoModal/index.tsx
  src/components/NewService/InfoModal/style.ts
  src/components/NewService/ServiceInfoModal.tsx
  src/components/NewService/index.tsx
  src/components/NewService/style.ts
  src/components/common/Input/style.ts
Labels: ⚡️Type: Performance, ♻️ Type: Refactor, 🎨 Type: Publishing, 2️⃣ Priority: Medium

#86 🔀 노션페이지 반응형 추가
  src/components/InstructionPage/index.tsx
  src/components/InstructionPage/style.ts
Labels: ♻️ Type: Refactor, 🎨 Type: Publishing, 2️⃣ Priority: Medium

#87 🔀 프로필 페이지 리디자인
  public/svg/CopyButton.tsx
  public/svg/CopyIcon.tsx
  public/svg/ErrorIcon.tsx
  public/svg/FixIcon.tsx
  public/svg/ModifyProfile.tsx
  public/svg/ProfileSmallFace.tsx
  public/svg/index.ts
  src/Atom/Atoms.tsx
  src/components/MyProfilePage/Profile.tsx
  src/components/MyProfilePage/index.tsx
  src/components/MyProfilePage/style.ts
  src/components/MyServiceList/Delete/index.tsx
  src/components/MyServiceList/Delete/style.ts
  src/components/MyServiceList/EmptyList.tsx
  src/components/MyServiceList/ListItem.tsx
  src/components/MyServiceList/Modify/index.tsx
  src/components/MyServiceList/Modify/style.ts
  src/components/MyServiceList/ModifyMyService.tsx
  src/components/MyServiceList/index.tsx
  src/components/MyServiceList/style.ts
  src/components/Sidebar/style.ts
  src/components/common/Portal/style.ts
  src/hooks/useUser.ts
  src/types/FixModalType.ts
  src/types/SignUpType.ts
Labels: ✨ Type: Feature, ⚡️Type: Performance, ♻️ Type: Refactor, 🎨 Type: Publishing, 2️⃣ Priority: Medium

#89 🔀 useFetch hook 추가
  src/hooks/useFetch.ts
  src/types/hooks/useFetch.ts
Labels: ✨ Type: Feature

#90 🔀 내 서비스 리스트 스타일 수정
  src/components/MyServiceList/Delete/style.ts
  src/components/MyServiceList/Modify/style.ts
  src/components/MyServiceList/style.ts
  src/components/Sidebar/style.ts
  src/components/common/Input/index.tsx
  src/components/common/Input/style.ts
Labels: 🐞 Type: Bug, ⚡️Type: Simple

#92 🔀 패스워드 타입 토글 버튼 아이콘 추가
  public/svg/CloseIcon.tsx
  public/svg/OpenIcon.tsx
  public/svg/index.ts
  src/components/NewSignIn/index.tsx
  src/components/common/Auth/NewPasswordCommon.tsx
Labels: 🎨 Type: Publishing, ⚡️Type: Simple, 3️⃣ Priority: Low

#93 🔀 API요청 useFetch수정
  src/api/TokenManger.ts
  src/api/index.ts
  src/components/MyProfilePage/Profile.tsx
  src/components/MyServiceList/Delete/index.tsx
  src/components/MyServiceList/Modify/index.tsx
  src/components/NewFindPsw/NewPassword.tsx
  src/components/NewService/index.tsx
  src/components/NewSignIn/index.tsx
  src/components/NewSignUp/Profile.tsx
  src/components/ServiceList/ListTable.tsx
  src/components/Sidebar/index.tsx
  src/components/common/Auth/SearchEmail.tsx
  src/components/common/Auth/VerifyEmail.tsx
  src/hooks/useFetch.ts
  src/types/API/GetService.ts
  src/types/API/OauthCode.ts
  src/types/TokenType.ts
  src/types/hooks/useFetch.ts
Labels: ♻️ Type: Refactor, 2️⃣ Priority: Medium

#97 🔀 서비스 생성시 에러 메시지 중복 버그 수정
  src/components/NewService/InfoModal/index.tsx
  src/components/NewService/InfoModal/style.ts
  src/components/NewService/index.tsx
Labels: ⚡️Type: Simple, 2️⃣ Priority: Medium

#96 🔀 Release/1.2.0
  public/svg/AddServiceFormImg.tsx
  public/svg/CheckIcon.tsx
  public/svg/CloseIcon.tsx
  public/svg/CopyButton.tsx
  public/svg/CopyIcon.tsx
  public/svg/ErrorIcon.tsx
  public/svg/FixIcon.tsx
  public/svg/ModifyProfile.tsx
  public/svg/OpenIcon.tsx
  public/svg/ProfileSmallFace.tsx
  public/svg/index.ts
  src/Atom/Atoms.tsx
  src/api/TokenManger.ts
  src/api/index.ts
  src/components/InstructionPage/index.tsx
  src/components/InstructionPage/style.ts
  src/components/MyProfilePage/Profile.tsx
  src/components/MyProfilePage/index.tsx
  src/components/MyProfilePage/style.ts
  src/components/MyServiceList/Delete/index.tsx
  src/components/MyServiceList/Delete/style.ts
  src/components/MyServiceList/EmptyList.tsx
  src/components/MyServiceList/ListItem.tsx
  src/components/MyServiceList/Modify/index.tsx
  src/components/MyServiceList/Modify/style.ts
  src/components/MyServiceList/ModifyMyService.tsx
  src/components/MyServiceList/index.tsx
  src/components/MyServiceList/style.ts
  src/components/NewFindPsw/NewPassword.tsx
  src/components/NewService/InfoModal/Info.tsx
  src/components/NewService/InfoModal/index.tsx
  src/components/NewService/InfoModal/style.ts
  src/components/NewService/ServiceInfoModal.tsx
  src/components/NewService/index.tsx
  src/components/NewService/style.ts
  src/components/NewSignIn/index.tsx
  src/components/NewSignUp/Profile.tsx
  src/components/ServiceList/ListTable.tsx
  src/components/Sidebar/index.tsx
  src/components/Sidebar/style.ts
  src/components/common/Auth/NewPasswordCommon.tsx
  src/components/common/Auth/SearchEmail.tsx
  src/components/common/Auth/VerifyEmail.tsx
  src/components/common/Input/index.tsx
  src/components/common/Input/style.ts
  src/components/common/Portal/index.tsx
  src/components/common/Portal/style.ts
  src/hooks/useFetch.ts
  src/hooks/useUser.ts
  src/types/API/GetService.ts
  src/types/API/OauthCode.ts
  src/types/FixModalType.ts
  src/types/SignUpType.ts
  src/types/TokenType.ts
  src/types/hooks/useFetch.ts
Labels: 📝 Type: Docs, 🌏 Type: Deploy

#104 🔀 GAuth title 변경
  src/pages/_app.tsx
Labels: ♻️ Type: Refactor, ⚡️Type: Simple, 3️⃣ Priority: Low

#99 🔀 리스트 없음 컴포넌트 반응형 추가
  src/components/MyServiceList/style.ts
Labels: 🎨 Type: Publishing, ⚡️Type: Simple
