Repository GSM-MSG/GAuth-FrontEnd, pull requests merged in 2023-07, with the labels that each got.

#152 wrap alarm svg
  src/components/Stulist/Header/index.tsx
  src/components/common/StuListFilter/style.ts
Labels: ⚡️Type: Simple, 2️⃣ Priority: Medium

#155 🔀 등록한 서비스가 없을 때 삭제버튼 hide 처리
  src/components/MyServiceList/index.tsx
Labels: 🐞 Type: Bug

#153 🔀 내가 등록한 서비스 수정 UI 변경
  src/components/MyServiceList/ListItem.tsx
  src/components/MyServiceList/style.ts
Labels: 🎨 Type: Publishing

#158 🔀 내 서비스를 서비스 창 클릭으로 수정하기
  src/components/MyServiceList/ListItem.tsx
Labels: ♻️ Type: Refactor, ⚡️Type: Simple

#159 🔀 Deploy
  public/svg/CloseIcon.tsx
  public/svg/OpenIcon.tsx
  src/components/MyServiceList/ListItem.tsx
  src/components/MyServiceList/index.tsx
  src/components/MyServiceList/style.ts
  src/components/SignIn/index.tsx
  src/components/Stulist/Header/index.tsx
  src/components/common/StuListFilter/style.ts
Labels: 🌏 Type: Deploy

#161 🔀 이메일 인증 어법 수정
  src/components/common/Auth/VerifyEmail.tsx
Labels: ♻️ Type: Refactor, 🎨 Type: Publishing, ⚡️Type: Simple

#162 🔀 Deploy
  src/components/common/Auth/VerifyEmail.tsx
Labels: 🌏 Type: Deploy

#164 ♻️ Refactor 서비스 타이틀 수정
  src/components/MyProfilePage/index.tsx
Labels: ♻️ Type: Refactor, 🎨 Type: Publishing, ⚡️Type: Simple

#166 svg size modify
  public/svg/CloseIcon.tsx
  public/svg/OpenIcon.tsx
Labels: 🎨 Type: Publishing, ⚡️Type: Simple
