Repository GSM-MSG/GAuth-FrontEnd, pull requests merged in 2023-06, with the labels that each got.

#131 🔀 가입 수락된 유저 필터 스타일 수정
  src/components/common/StuListFilter/style.ts
Labels: ⚡️Type: Simple

#137 🔀 Sidebar 라우팅 오류 수정
  src/components/Sidebar/index.tsx
Labels: 🐞 Type: Bug, 0️⃣ Priority: Critical

#134 🔀 Stulist 전체 조회 기능 추가
  src/Atom/Atoms.tsx
  src/components/common/StuListFilter/index.tsx
  src/types/components/Sidebar.ts
Labels: ✨ Type: Feature, 1️⃣ Priority: High

#133 🔀 Components 폴더 리펙토링
  src/components/LoginPage/SideWave.tsx
  src/components/LoginPage/index.tsx
  src/components/LoginPage/style.ts
  src/components/SignIn/index.tsx
  src/components/SignIn/style.ts
  src/components/SignUp/NewPassword.tsx
  src/components/SignUp/Notion.tsx
  src/components/SignUp/Privacy.tsx
  src/components/SignUp/Profile.tsx
  src/components/SignUp/Success.tsx
  src/components/SignUp/index.tsx
  src/components/SignUp/style.ts
  src/components/SignUpPage/PrivacyConsent.tsx
  src/components/SignUpPage/WaveWrapper.tsx
  src/components/SignUpPage/index.tsx
  src/components/SignUpPage/style.ts
  src/components/Stulist/AddUser/Page/InsertGraduInfo/index.tsx
  src/components/Stulist/AddUser/Page/InsertStuInfo/index.tsx
  src/components/Stulist/AddUser/Page/InsertTeacherInfo/index.tsx
  src/components/Stulist/AddUser/Page/SelectGrade/index.tsx
  src/components/Stulist/SaveXlsx/index.tsx
  src/pages/login.tsx
  src/pages/signUp.tsx
Labels: ♻️ Type: Refactor

#140 🔀 내가 등록한 서비스 선택 삭제 기능 추가
  public/png/Check.png
  src/Atom/Atoms.tsx
  src/components/MyServiceList/Delete/index.tsx
  src/components/MyServiceList/Delete/style.ts
  src/components/MyServiceList/ListItem.tsx
  src/components/MyServiceList/index.tsx
  src/components/MyServiceList/style.ts
Labels: ✨ Type: Feature, 🎨 Type: Publishing

#146 modify filtering location
  src/components/common/StuListFilter/style.ts
Labels: 🎨 Type: Publishing

#149 🔀 로그인 요청 중일 때 재 요청 막는 로직 추가
  src/components/SignIn/index.tsx
Labels: ⚡️Type: Performance
