Repository GSM-MSG/GAuth-FrontEnd, pull requests merged in 2024-08, with the labels that each got.

#226 🔀 회원가입 시 학번, 이름 받기
  src/Atom/Atoms.tsx
  src/components/SignUp/Profile.tsx
  src/components/SignUp/StudentName.tsx
  src/components/SignUp/StudentNumber.tsx
  src/components/SignUp/index.tsx
  src/components/common/Auth/ChangePasswordCommon.tsx
  src/types/NumberForm.ts
Labels: ✨ Type: Feature

#225 🔀 프로필 이미지 수정 시 깜빡임 최소화
  src/components/MyProfilePage/Profile.tsx
Labels: ⚡️Type: Performance

#224 🔀 공동작업자 기능 및 디자인적 오류 해결
  src/components/MyServiceList/Modify/Assignment/index.tsx
  src/components/MyServiceList/Modify/CoWorkerModal/index.tsx
  src/components/MyServiceList/Modify/CoWorkerModal/style.ts
  src/components/MyServiceList/Modify/DeleteAssignment/index.tsx
  src/components/MyServiceList/Modify/index.tsx
  src/components/ServiceCo-WorkerList/Assignment/index.tsx
  src/components/ServiceCo-WorkerList/index.tsx
  src/components/ServiceCo-WorkerList/style.ts
Labels: 🐞 Type: Bug

#227 🔀Deploy
  src/Atom/Atoms.tsx
  src/components/MyProfilePage/Profile.tsx
  src/components/MyServiceList/Modify/Assignment/index.tsx
  src/components/MyServiceList/Modify/CoWorkerModal/index.tsx
  src/components/MyServiceList/Modify/CoWorkerModal/style.ts
  src/components/MyServiceList/Modify/DeleteAssignment/index.tsx
  src/components/MyServiceList/Modify/index.tsx
  src/components/ServiceCo-WorkerList/Assignment/index.tsx
  src/components/ServiceCo-WorkerList/index.tsx
  src/components/ServiceCo-WorkerList/style.ts
  src/components/SignUp/Profile.tsx
  src/components/SignUp/StudentName.tsx
  src/components/SignUp/StudentNumber.tsx
  src/components/SignUp/index.tsx
  src/components/common/Auth/ChangePasswordCommon.tsx
  src/types/NumberForm.ts
Labels: 🌏 Type: Deploy

#228 🔀 stulist seoconfig 추가
  src/pages/stulist.tsx
Labels: ⚡️Type: Simple

#229 🔀Deploy
  src/pages/stulist.tsx
Labels: 🌏 Type: Deploy
