Repository GSM-MSG/GAuth-FrontEnd, pull requests merged in 2024-06, with the labels that each got.

#214 🔀 공동작업자 추가 (서비스 등록 시)
  public/svg/AddBtn.tsx
  public/svg/AddCompleteBtn.tsx
  public/svg/AddMangerBlue.tsx
  public/svg/ChevronRight.tsx
  public/svg/index.ts
  src/Atom/Atoms.tsx
  src/components/NewService/ServiceOwnerList/index.tsx
  src/components/NewService/ServiceOwnerList/style.ts
  src/components/NewService/index.tsx
  src/components/NewService/style.ts
  src/types/ResAddService.ts
  src/types/SelectedUserType.ts
  src/types/index.ts
Labels: ✨ Type: Feature, 2️⃣ Priority: Medium

#212 🔀 로그인 페이지 버튼 debounce 처리
  src/components/SignIn/index.tsx
Labels: ✨ Type: Feature, ⚡️Type: Performance

#218 🔀 health check 기능 추가
  src/components/SignIn/HealthCheck/index.tsx
  src/components/SignIn/HealthCheck/style.ts
  src/components/SignIn/index.tsx
  src/components/SignUp/Success.tsx
  src/components/SignUp/style.ts
  src/components/common/Detail/index.tsx
  src/components/common/Detail/style.ts
Labels: ✨ Type: Feature

#219 🔀중복된 이메일 검사 기능 추가
  src/Atom/Atoms.tsx
  src/components/common/Auth/SearchEmail.tsx
Labels: ⚡️Type: Performance

#215 🔀 공동작업자 추가 (서비스 수정 시)
  public/svg/AddManager.tsx
  public/svg/AddPerson.tsx
  public/svg/RightArrow.tsx
  public/svg/index.ts
  src/Atom/Atoms.tsx
  src/components/MyServiceList/Modify/Assignment/index.tsx
  src/components/MyServiceList/Modify/Assignment/style.ts
  src/components/MyServiceList/Modify/CoWorkerModal/index.tsx
  src/components/MyServiceList/Modify/CoWorkerModal/style.ts
  src/components/MyServiceList/Modify/DeleteAssignment/index.tsx
  src/components/MyServiceList/Modify/DeleteAssignment/style.ts
  src/components/MyServiceList/Modify/index.tsx
  src/components/MyServiceList/Modify/style.ts
  src/components/ServiceCo-WorkerList/Assignment/index.tsx
  src/components/ServiceCo-WorkerList/Assignment/style.ts
  src/components/ServiceCo-WorkerList/index.tsx
  src/components/ServiceCo-WorkerList/style.ts
  src/components/Stulist/Header/index.tsx
  src/components/common/Auth/SearchEmail.tsx
  src/types/ServiceOwnerModalType.ts
  src/types/components/ServiceOwnerModalType.ts
Labels: ✨ Type: Feature
